name: PoliteTeleports
main: jasonw4331\PoliteTeleports\Main
src-namespace-prefix: jasonw4331\PoliteTeleports
version: 2.1.3
api: [4.0.0, 5.0.0]
description: "A plugin which allows players to politely ask for a teleport"
author: "jasonw4331"

permissions:
  PoliteTeleports.command.tpask:
    default: true
    description: "Allows the player to use /tpask"
  PoliteTeleports.command.tpaccept:
    default: true
    description: "Allows the player to use /tpaccept"
  PoliteTeleports.command.tpahere:
    default: true
    description: "Allows the player to use /tpahere"
  PoliteTeleports.command.tpconfig:
    default: true
    description: "Allows the player to use /tpconfig"
  PoliteTeleports.command.tpconfig.language:
    default: op
    description: "Allows the player to set /tpconfig language"
  PoliteTeleports.command.tpdeny:
    default: true
    description: "Allows the player to use /tpdeny"
  PoliteTeleports.command.tprandom:
    default: true
    description: "Allows the player to use /tprandom"